language: objective-c
cache:
  yarn: true
  directories:
    - node_modules
env:
  - NODE_VERSION="8.9.4"
before_install:
  # Install Node.js
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version

install:
  - yarn

before_deploy:
  - npm run pack

deploy:
  provider: releases
  skip_cleanup: true
  file:
    - dist/*.exe
    - dist/*.dmg
  on:
    tags: true
